### ISSUE TITLE
App points to URL/main.js

### ISSUE THREAD

**Issue by tgoldenberg** [fractal-code/meteor-azure#16]
After successfully deploying to Web App and configuring domain name and https, my `/` route now redirects to `/main.js`. This, of course, causes an error with `react-router`, since it doesn't recognize the route. Any idea why this happens?

**Comment by ramijarrar** [comment]
This looks very similar to #11

Can you paste your web.config? The 'force https' rule needs to be added at the beginning of the rewrite section in order to function properly (as per the [example](https://raw.githubusercontent.com/talos-code/meteor-azure-example/master/.config/azure/web.config) provided)

**Comment by tgoldenberg** [comment]
Yes, it looks like that issue addresses this. Sorry for overlooking it.
