### ISSUE TITLE
Run meteor-azure after Github push?

### ISSUE THREAD

**Issue by conradj** [fractal-code/meteor-azure#49]
Thanks for creating a great tool! Is there a canonical method you can point me at for running meteor-azure from the App Service, rather than locally? I'd like to automatically deploy after pushing to Github. Do I have to use a separate CI service or can I do it directly in Azure/Kudu?

**Comment by ramijarrar** [comment]
You'll need to configure a separate CI to run the deployment after Github push. This should be very straight-forward with free plans on CircleCI, Codeship, etc. (just install Meteor/local node modules and run the `meteor-azure` command).

FYI the tool was originally written for the built-in Kudu interface, but we had to drop this in v2 due to slow builds and many inherent UX pain-points (see release notes [here](https://github.com/fractal-code/meteor-azure/releases/tag/v2.0.0)).

**Comment by conradj** [comment]
Great, thanks for the tips and background info. Will give CircleCI etc a go.
