### ISSUE TITLE
Deployment fails on Bitbucket pipelines

### ISSUE THREAD

**Issue by XAMelleOH** [fractal-code/meteor-azure#61]
For some reason, around 10 days ago, running meteor-azure on Bitbucket pipelines stopped working. Actually it freezes at some step, visible at screenshot:

![image 1](https://user-images.githubusercontent.com/283614/47205862-da3cc580-d38f-11e8-82a2-76b9899b4fe6.png)

Previously everything was relatively fine: 

![image 2](https://user-images.githubusercontent.com/283614/47205919-01939280-d390-11e8-9afb-79b0c1e07aba.png)

I say `relatively` because it was often freezed at `info:    hearing-is-believing-dev: Polling server status...` and could be in that state for hours, never reporting FINISHED status back, but actually deployment was fine.

But now, it always freezes at the same stage and deploy never happening

All packages are latest version.

**Comment by ramijarrar** [comment]
It seems like the build is being cut off due to the 20 minute time limit on Bitbucket (which is not that long for large apps especially with legacy atmosphere deps) - are you able to confirm if this is an issue when deploying `meteor create --bare`?

The deploy process runs completely locally, so no changes from our end that could suddenly cause  this to break.

**Comment by XAMelleOH** [comment]
Ok, you was right: it took 40 minutes...
